builds:
- main: cmd/server/server.go
  binary: doggo-server
  goos:
    - darwin
    - linux
  goarch:
    - amd64
- main: cmd/client/client.go
  binary: doggo-client
  goos:
    - darwin
    - linux
  goarch:
    - amd64
dockers:
- binary: doggo-server
  image: rossedman/doggo-server
  goos: linux
  goarch: amd64
  dockerfile: Dockerfile.server
  tag_templates:
  - latest
- binary: doggo-client
  image: rossedman/doggo-client
  goos: linux
  goarch: amd64
  dockerfile: Dockerfile.client
  tag_templates:
  - "latest"